# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20161230_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_owner', to='business.Business'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_paid', to='business.Business'),
        ),
    ]
