# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_is_deleted'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='user',
        ),
        migrations.AddField(
            model_name='outlet',
            name='business',
            field=models.ForeignKey(default='0f45768e-cdc8-4d41-9e02-5fd846441633', on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
    ]
