# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('reference_number', models.CharField(max_length=100, null=True)),
                ('registration_number', models.CharField(help_text='Of the business', max_length=200, unique=True)),
                ('description', models.CharField(help_text='describe the business', max_length=200, null=True)),
                ('physical_address', models.CharField(max_length=200, null=True)),
                ('certificate', models.ImageField(null=True, upload_to='business_certificates/%Y/%m/%d/')),
                ('national_id_photo', models.ImageField(null=True, upload_to='national_id_photos/%Y/%m/%d/')),
                ('kra_pin_certificate', models.ImageField(null=True, upload_to='kra_pins/%Y/%m/%d/')),
            ],
        ),
    ]
