# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(default=1, help_text='describe the business', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='physical_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
