# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170103_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
