# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='level',
            field=models.IntegerField(default=0, help_text='business types'),
        ),
    ]
