# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
        ('orders', '0003_auto_20161211_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
            preserve_default=False,
        ),
    ]
