# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1, help_text='Order Number', unique=True),
            preserve_default=False,
        ),
    ]
