# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20161219_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
