# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=320)),
                ('priority', models.SmallIntegerField(default=3)),
                ('message_type', models.SmallIntegerField(default=1)),
                ('message_status', models.SmallIntegerField(default=0)),
                ('delivery_response', models.CharField(max_length=100, null=True)),
                ('request_id', models.CharField(max_length=300, null=True)),
                ('sender_address', models.CharField(max_length=100)),
                ('recipient_address', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
