# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Categories such as Unga,Laptop,Phone ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='E.g Electronics, Households', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Such as Kgs,Litres e.t.c', max_length=100, unique=True),
        ),
    ]
