# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161203_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='price_per_unit',
        ),
    ]
