# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161203_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
