# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20161204_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_name',
            field=models.CharField(help_text='E.g Kg. ', max_length=100, null=True),
        ),
    ]
