# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20161205_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='product_images/%Y/%m/%d/'),
        ),
    ]
