# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
        ('products', '0011_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
            preserve_default=False,
        ),
    ]
