# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_is_deleted'),
        ('products', '0018_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(default='c75e7202-b0a6-4649-99c6-f2c02af121b2', on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
    ]
