# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='commission',
            field=models.IntegerField(default=0, help_text='% age commission for calculating selling price '),
        ),
    ]
