# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20170103_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Unit'),
            preserve_default=False,
        ),
    ]
